[package]
name = "quicktrack"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite", "macros", "migrate", "chrono"] }
tui-input = "0.11.1"
features = "0.10.0"
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["cargo"] }
